### ISSUE TITLE
Undocumented code objects

### ISSUE THREAD

**Issue by ohagen** [8Ginette8/gbif.range#11]
W  checking for missing documentation entries (436ms)
   Undocumented code objects:
     'countries' 'eco.earth' 'eco.fresh' 'eco.marine' 'rst' 'shp.lonlat'
   Undocumented data sets:
     'eco.earth' 'eco.fresh' 'eco.marine' 'rst' 'countries' 'shp.lonlat'
   All user-level objects in a package should have documentation entries.
   See chapter 'Writing R documentation files' in the 'Writing R
   Extensions' manual.

**Comment by 8Ginette8** [comment]
Hum did not know it was a requirement. In any case 'countries' needs to be removed...

**Comment by 8Ginette8** [comment]
No warnings anymore, solved since a while now
