### ISSUE TITLE
Does not work even with the example

### ISSUE THREAD

**Issue by karolazvdo** [8Ginette8/gbif.range#14]
I've been trying to get the range for some animals for my thesis. But even when I try to execute the example presented, to understand how could I use this package for my study, the example does not work.

When I run the function **get_gbif**, the package returns an empty object with the follow output:

``obs.pt = get_gbif(sp_name="Panthera tigris",
                   basis=c("OBSERVATION","HUMAN_OBSERVATION","MACHINE_OBSERVATION"))``

> >>>>>>>> Total number of records: 4236 
...GBIF records of Panthera tigris : download of all records starting... 
100 %...
---> Grain filtering...
Records removed: 3440 
---> Removal of duplicated records... 
Records removed: 344 
---> Removal of absence records... 
Records removed: 14 
---> Basis of records selection... 
Records removed: 429 
---> Time period selection... 
Records removed: 0 
No records left after selection... 

How can I get the range if I can't even get the occurrence??

**Comment by 8Ginette8** [comment]
Hi there,

I apologize, we are in the process of updating the package, it's not surprising that you run into issues. I can have a look tomorrow and tell you what's wrong.

Best,
Yohann

**Comment by mbarkdull** [comment]
I am also having this issue.

**Comment by 8Ginette8** [comment]
Hi there,

Everything should be running smoothly from now on. Just keep in mind that evaluation functions such as cross validation are not yet implemented, as this the next steps of the package development. Let me know if you run (or not) into any problems so I can close this issue.

Best,
Yohann

**Comment by mbarkdull** [comment]
Hi @8Ginette8, 

The code as posted on GitHub does work for me now; however, when I uninstall and reinstall the package, I'm not getting the fix. Not sure what is going on there. 

Thanks!

**Comment by 8Ginette8** [comment]
Hi there,

Hum that's odd, everything works on our side as we tried on several laptops after your comment. I have updated the examples, maybe it was that. Let me know.

Best,
Yohann

**Comment by 8Ginette8** [comment]
I will close it, just update me in case you run into some issues again
