### ISSUE TITLE
data size mighty be a problem... currently ~72Mb

### ISSUE THREAD

**Issue by ohagen** [8Ginette8/gbif.range#5]
Packages should be of the minimum necessary size. Reasonable compression should be used for data (not just .rda files) and PDF documentation: CRAN will if necessary pass the latter through qpdf.

As a general rule, neither data nor documentation should exceed 5MB (which covers several books). A CRAN package is not an appropriate way to distribute course notes, and authors will be asked to trim their documentation to a maximum of 5MB.

Where a large amount of data is required (even after compression), consideration should be given to a separate data-only package which can be updated only rarely (since older versions of packages are archived in perpetuity).

Similar considerations apply to other forms of “data”, e.g., .jar files.

Source package tarballs should if possible not exceed 10MB. It is much preferred that third-party source software should be included within the package (as e.g. a vendor.tar.xz file) than be downloaded at installation: if this requires a larger tarball a modestly increased limit can be requested at submission. 

Ww must solve these in order to make it into CRAN:
ecoregions.RDatab (70Mb), exrst.RData (2Mb).

**Comment by ohagen** [comment]
prob we will have to make a shape-file download and even support community based link maintenance...

**Comment by 8Ginette8** [comment]
- I have added the links that you need for the ecoregion shapefiles
- From "geo_dat.Rdata", only "shp.lonlat" should be kept as separate object that needs to be loaded in the package for the example (the shapefile you need is in the data folder --> "shp_lonlat.x")
- I removed "var_select_XYtest.RData" which was not needed
- "exrst.RData" should be replaced with "rst.tif" as file loaded within the package for the example (you can find it in the data folder too). It has less layers (only bio) than before and is therefore lighter.
- Actually we also need to add "rst_enl.tif" which is the same with a larger extent...Could be also used for the examples

**Comment by 8Ginette8** [comment]
Closing it, the other issues are already addressing this problem (removal of ecoregions.RData and URL pipeline)
