### ISSUE TITLE
download proceedure

### ISSUE THREAD

**Issue by ohagen** [8Ginette8/gbif.range#6]
@8Ginette8 plz send me the links to download with the names you wanna call it.

**Comment by ohagen** [comment]
Thanks! 

I will probably try to use this package: https://cran.r-project.org/web/packages/pkgfilecache/vignettes/pkgfilecache.html

I started listing all the MD5 but dont think with will be necessary for now... maybe not good to include if they keep updating things on their side... although we have to ship gbif.range with a guarantee

File from:
https://www.arcgis.com/sharing/rest/content/items/b1636d640ede4d6ca8f5e369f2dc368b/data

MD5: 
90e8eb3e93dac44e1606cb9ebaa3b8f9

on it...

**Comment by 8Ginette8** [comment]
Interesting link...https://stackoverflow.com/questions/14871818/package-that-downloads-data-from-the-internet-during-installation

**Comment by ohagen** [comment]
@ #2cc877d
