### ISSUE TITLE
compress example database

### ISSUE THREAD

**Issue by ohagen** [8Ginette8/gbif.range#8]
Double check and compress the examples? maybe less variables?

**Comment by ohagen** [comment]
can you aggregate the env. var or at least not use so many variables?

**Comment by 8Ginette8** [comment]
From the new rst.tif and rst_enl.tif? Is it still too much? We only have 350KB now should be fine no?

**Comment by 8Ginette8** [comment]
Removing it, we solved it last time by thinning down the ones we need. For ecoregions.RData we can remove it once you have set up the download pipeline (see other issue).
