### ISSUE TITLE
NAMESPACE - importFrom(mclust,mclustBIC)

### ISSUE THREAD

**Issue by 8Ginette8** [8Ginette8/gbif.range#9]
The code line "importFrom(mclust,mclustBIC)" needs to be always in there, otherwise get_range does not work...This or another solution...

**Comment by 8Ginette8** [comment]
range.tiger = get_range(sp_name="Panthera tigris",
+                         occ_coord=obs.pt,
+                         Bioreg=eco.earth,
+                         Bioreg_name="ECO_NAME")
## Start of computation for species:  Panthera tigris  ### 
4 outlier's from 155 | proportion from total points: 3%
Bioregion 1  of  9 :  Brahmaputra Valley Semi-Evergreen Forests 
Error in mclustBIC(data = c(1093.3565, 1093.3538, 1091.0011, 1091.2166,  : 
  could not find function "mclustBIC"

---> The error is this

**Comment by ohagen** [comment]
mclust moved to depends
